// ============================================================
// data.js — Banco de dados estático do jogo
// Países, ligas, clubes, nomes, formações, patrocinadores, i18n
// ============================================================

export const DB_VERSION = 1;

// -------------------- PAÍSES / CONFEDERAÇÕES --------------------
export const COUNTRIES = [
  { id: 'br', name: 'Brasil', flag: '🇧🇷', confed: 'america', ntRep: 86 },
  { id: 'ar', name: 'Argentina', flag: '🇦🇷', confed: 'america', ntRep: 90 },
  { id: 'uy', name: 'Uruguai', flag: '🇺🇾', confed: 'america', ntRep: 78 },
  { id: 'co', name: 'Colômbia', flag: '🇨🇴', confed: 'america', ntRep: 79 },
  { id: 'mx', name: 'México', flag: '🇲🇽', confed: 'america', ntRep: 74 },
  { id: 'us', name: 'EUA', flag: '🇺🇸', confed: 'america', ntRep: 73 },
  { id: 'pt', name: 'Portugal', flag: '🇵🇹', confed: 'europa', ntRep: 86 },
  { id: 'es', name: 'Espanha', flag: '🇪🇸', confed: 'europa', ntRep: 91 },
  { id: 'en', name: 'Inglaterra', flag: '🏴', confed: 'europa', ntRep: 90 },
  { id: 'fr', name: 'França', flag: '🇫🇷', confed: 'europa', ntRep: 90 },
  { id: 'de', name: 'Alemanha', flag: '🇩🇪', confed: 'europa', ntRep: 87 },
  { id: 'it', name: 'Itália', flag: '🇮🇹', confed: 'europa', ntRep: 85 },
  { id: 'nl', name: 'Holanda', flag: '🇳🇱', confed: 'europa', ntRep: 82 },
  { id: 'be', name: 'Bélgica', flag: '🇧🇪', confed: 'europa', ntRep: 80 },
  { id: 'hr', name: 'Croácia', flag: '🇭🇷', confed: 'europa', ntRep: 80 },
  { id: 'rs', name: 'Sérvia', flag: '🇷🇸', confed: 'europa', ntRep: 75 },
  { id: 'jp', name: 'Japão', flag: '🇯🇵', confed: 'asia', ntRep: 76 },
  { id: 'kr', name: 'Coreia do Sul', flag: '🇰🇷', confed: 'asia', ntRep: 75 },
  { id: 'ng', name: 'Nigéria', flag: '🇳🇬', confed: 'africa', ntRep: 77 },
  { id: 'sn', name: 'Senegal', flag: '🇸🇳', confed: 'africa', ntRep: 76 },
  { id: 'ma', name: 'Marrocos', flag: '🇲🇦', confed: 'africa', ntRep: 77 },
  { id: 'eg', name: 'Egito', flag: '🇪🇬', confed: 'africa', ntRep: 74 },
];

// -------------------- LIGAS --------------------
// tier 1 = primeira divisão; tier 2 = segunda (com acesso/rebaixamento)
export const LEAGUES = [
  { id: 'br1', country: 'br', name: 'Campeonato Brasileiro Série A', tier: 1, teams: 20, relegation: 4 },
  { id: 'br2', country: 'br', name: 'Campeonato Brasileiro Série B', tier: 2, teams: 20, relegation: 4 },
  { id: 'br3', country: 'br', name: 'Campeonato Brasileiro Série C', tier: 3, teams: 20, relegation: 4 },
  { id: 'br4', country: 'br', name: 'Campeonato Brasileiro Série D', tier: 4, teams: 20 },
  { id: 'ar1', country: 'ar', name: 'Liga Profesional Argentina', tier: 1, teams: 20 },
  { id: 'en1', country: 'en', name: 'Premier League', tier: 1, teams: 20 },
  { id: 'es1', country: 'es', name: 'La Liga', tier: 1, teams: 20 },
  { id: 'it1', country: 'it', name: 'Serie A Italiana', tier: 1, teams: 20 },
  { id: 'de1', country: 'de', name: 'Bundesliga', tier: 1, teams: 18 },
  { id: 'fr1', country: 'fr', name: 'Ligue 1', tier: 1, teams: 18 },
  { id: 'pt1', country: 'pt', name: 'Liga Portugal', tier: 1, teams: 18 },
  { id: 'nl1', country: 'nl', name: 'Eredivisie', tier: 1, teams: 18 },
];

// -------------------- CLUBES --------------------
// Formato: [nome, abrev, cidade, cor1, cor2, reputação(1-99), estádio, capacidade]
// Os escudos são gerados proceduralmente em SVG (ver gen.js) a partir das cores/abrev.
export const CLUBS = {
  br1: [
    ['Flamengo', 'FLA', 'Rio de Janeiro', '#c1121f', '#111111', 93, 'Maracanã', 78],
    ['Palmeiras', 'PAL', 'São Paulo', '#006437', '#ffffff', 91, 'Allianz Parque', 43],
    ['São Paulo', 'SAO', 'São Paulo', '#e30613', '#111111', 88, 'Morumbis', 66],
    ['Corinthians', 'COR', 'São Paulo', '#111111', '#ffffff', 89, 'Neo Química Arena', 49],
    ['Fluminense', 'FLU', 'Rio de Janeiro', '#7a003c', '#006437', 86, 'Maracanã', 78],
    ['Botafogo', 'BOT', 'Rio de Janeiro', '#111111', '#ffffff', 85, 'Nilton Santos', 46],
    ['Atlético Mineiro', 'CAM', 'Belo Horizonte', '#111111', '#ffffff', 86, 'Arena MRV', 46],
    ['Grêmio', 'GRE', 'Porto Alegre', '#0d80bf', '#111111', 86, 'Arena do Grêmio', 55],
    ['Internacional', 'INT', 'Porto Alegre', '#d40000', '#ffffff', 85, 'Beira-Rio', 50],
    ['Cruzeiro', 'CRU', 'Belo Horizonte', '#003aaf', '#ffffff', 85, 'Mineirão', 61],
    ['Athletico Paranaense', 'CAP', 'Curitiba', '#d40000', '#111111', 82, 'Ligga Arena', 42],
    ['Fortaleza', 'FOR', 'Fortaleza', '#1c4f9c', '#e30613', 79, 'Castelão', 63],
    ['Red Bull Bragantino', 'RBB', 'Bragança Paulista', '#e30613', '#ffffff', 78, 'Nabi Abi Chedid', 17],
    ['Santos', 'SAN', 'Santos', '#ffffff', '#111111', 84, 'Vila Belmiro', 16],
    ['Vasco da Gama', 'VAS', 'Rio de Janeiro', '#111111', '#ffffff', 83, 'São Januário', 21],
    ['Bahia', 'BAH', 'Salvador', '#003aaf', '#e30613', 80, 'Arena Fonte Nova', 47],
    ['Cuiabá', 'CUI', 'Cuiabá', '#086b33', '#f5d100', 70, 'Arena Pantanal', 44],
    ['Juventude', 'JUV', 'Caxias do Sul', '#006437', '#ffffff', 68, 'Alfredo Jaconi', 19],
    ['Vitória', 'VIT', 'Salvador', '#e30613', '#111111', 74, 'Barradão', 34],
    ['Ceará', 'CEA', 'Fortaleza', '#111111', '#ffffff', 72, 'Castelão', 63],
  ],
  br2: [
    ['Coritiba', 'CFC', 'Curitiba', '#006437', '#ffffff', 74, 'Couto Pereira', 40],
    ['Sport Recife', 'SPO', 'Recife', '#e30613', '#111111', 75, 'Ilha do Retiro', 32],
    ['América Mineiro', 'AME', 'Belo Horizonte', '#006437', '#ffffff', 72, 'Independência', 23],
    ['Goiás', 'GOI', 'Goiânia', '#006437', '#ffffff', 72, 'Serrinha', 14],
    ['Ponte Preta', 'PON', 'Campinas', '#111111', '#ffffff', 70, 'Moisés Lucarelli', 19],
    ['Guarani', 'GUA', 'Campinas', '#006437', '#ffffff', 70, 'Brinco de Ouro', 29],
    ['CRB', 'CRB', 'Maceió', '#e30613', '#ffffff', 66, 'Rei Pelé', 17],
    ['Vila Nova', 'VIL', 'Goiânia', '#e30613', '#ffffff', 68, 'Onésio Brasileiro Alvarenga', 8],
    ['Chapecoense', 'CHA', 'Chapecó', '#008f4c', '#ffffff', 70, 'Arena Condá', 20],
    ['Avaí', 'AVA', 'Florianópolis', '#0068b7', '#ffffff', 68, 'Ressacada', 17],
    ['Criciúma', 'CRI', 'Criciúma', '#f5d100', '#111111', 68, 'Heriberto Hülse', 19],
    ['Mirassol', 'MIR', 'Mirassol', '#006437', '#f5d100', 67, 'José Maria de Campos Maia', 15],
    ['Novorizontino', 'NOV', 'Novo Horizonte', '#f5d100', '#111111', 66, 'Jorge Ismael de Biasi', 16],
    ['Paysandu', 'PAY', 'Belém', '#0d80bf', '#ffffff', 70, 'Curuzu', 16],
    ['Botafogo-SP', 'BSP', 'Ribeirão Preto', '#e30613', '#111111', 64, 'Santa Cruz', 29],
    ['Operário Ferroviário', 'OPE', 'Ponta Grossa', '#111111', '#ffffff', 62, 'Germano Krüger', 10],
    ['Ituano', 'ITU', 'Itu', '#e30613', '#111111', 62, 'Novelli Júnior', 18],
    ['ABC', 'ABC', 'Natal', '#111111', '#ffffff', 63, 'Frasqueirão', 15],
    ['Londrina', 'LON', 'Londrina', '#0d80bf', '#ffffff', 63, 'Estádio do Café', 30],
    ['Sampaio Corrêa', 'SAM', 'São Luís', '#e30613', '#f5d100', 62, 'Castelão (MA)', 40],
  ],
  br3: [
    ['Anápolis', 'ANA', 'Anápolis', '#111111', '#ffffff', 54, 'Jonas Duarte', 10],
    ['Amazonas', 'AMA', 'Manaus', '#006437', '#f5d100', 62, 'Arena da Amazônia', 44],
    ['Barra Futebol Clube', 'BAR', 'Balneário Camboriú', '#111111', '#f5d100', 59, 'Hercílio Luz', 10],
    ['Botafogo-PB', 'BPB', 'João Pessoa', '#111111', '#ffffff', 61, 'Almeidão', 25],
    ['Brusque', 'BRU', 'Brusque', '#f5a800', '#111111', 68, 'Augusto Bauer', 5],
    ['Caxias', 'CAX', 'Caxias do Sul', '#7a003c', '#ffffff', 64, 'Centenário', 22],
    ['Confiança', 'CON', 'Aracaju', '#003aaf', '#ffffff', 59, 'Batistão', 15],
    ['Ferroviária', 'AFE', 'Araraquara', '#7a003c', '#ffffff', 60, 'Fonte Luminosa', 12],
    ['Figueirense', 'FIG', 'Florianópolis', '#111111', '#ffffff', 62, 'Orlando Scarpelli', 19],
    ['Floresta', 'FLO', 'Fortaleza', '#006437', '#ffffff', 56, 'Presidente Vargas', 20],
    ['Guarani', 'GUA', 'Campinas', '#006437', '#ffffff', 70, 'Brinco de Ouro', 29],
    ['Inter de Limeira', 'INT', 'Limeira', '#111111', '#ffffff', 58, 'Major José Levy Sobrinho', 18],
    ['Itabaiana', 'ITA', 'Itabaiana', '#003aaf', '#e30613', 53, 'Etelvino Mendonça', 10],
    ['Ituano', 'ITU', 'Itu', '#e30613', '#111111', 62, 'Novelli Júnior', 18],
    ['Maranhão', 'MAC', 'São Luís', '#006437', '#f5d100', 58, 'Castelão', 40],
    ['Maringá', 'MAR', 'Maringá', '#111111', '#ffffff', 61, 'Willie Davids', 16],
    ['Paysandu', 'PAY', 'Belém', '#0d80bf', '#ffffff', 70, 'Curuzu', 16],
    ['Santa Cruz', 'SAN', 'Recife', '#111111', '#ffffff', 72, 'Arruda', 60],
    ['Volta Redonda', 'VRE', 'Volta Redonda', '#f5d100', '#111111', 60, 'Raulino de Oliveira', 18],
    ['Ypiranga', 'YPI', 'Erechim', '#f5d100', '#003aaf', 58, 'Colosso da Lagoa', 22],
  ],
  br4: [
    ['Nacional', 'NACA', 'Manaus', '#003aaf', '#ffffff', 54, 'Estádio Nacional', 3],
    ['Manaus', 'MANA', 'Manaus', '#e30613', '#ffffff', 52, 'Estádio Manaus', 5],
    ['Manauara', 'MANA', 'Manaus', '#006437', '#ffffff', 50, 'Estádio Manauara', 7],
    ['GAS', 'GASR', 'Boa Vista', '#111111', '#f5d100', 48, 'Estádio GAS', 9],
    ['Monte Roraima', 'MONR', 'Boa Vista', '#7a003c', '#ffffff', 46, 'Estádio Monte Roraima', 11],
    ['São Raimundo', 'SÃOR', 'Boa Vista', '#f5d100', '#111111', 44, 'Estádio São Raimundo', 13],
    ['Independência', 'INDA', 'Rio Branco', '#0d80bf', '#ffffff', 54, 'Estádio Independência', 15],
    ['Galvez', 'GALA', 'Rio Branco', '#003aaf', '#ffffff', 52, 'Estádio Galvez', 17],
    ['Humaitá', 'HUMA', 'Rio Branco', '#e30613', '#ffffff', 50, 'Estádio Humaitá', 19],
    ['Porto Velho', 'PORR', 'Porto Velho', '#006437', '#ffffff', 48, 'Estádio Porto Velho', 3],
    ['Guaporé', 'GUAR', 'Porto Velho', '#111111', '#f5d100', 46, 'Estádio Guaporé', 5],
    ['Araguaína', 'ARAT', 'Araguaína', '#7a003c', '#ffffff', 44, 'Estádio Araguaína', 7],
    ['Gama', 'GAMD', 'Brasília', '#f5d100', '#111111', 54, 'Estádio Gama', 9],
    ['Brasiliense', 'BRAD', 'Brasília', '#0d80bf', '#ffffff', 52, 'Estádio Brasiliense', 11],
    ['Luverdense', 'LUVM', 'Cuiabá', '#003aaf', '#ffffff', 50, 'Estádio Luverdense', 13],
    ['Primavera', 'PRIM', 'Cuiabá', '#e30613', '#ffffff', 48, 'Estádio Primavera', 15],
    ['Inhumas', 'INHG', 'Goiânia', '#006437', '#ffffff', 46, 'Estádio Inhumas', 17],
    ['Aparecidense', 'APAG', 'Goiânia', '#111111', '#f5d100', 44, 'Estádio Aparecidense', 19],
    ['Capital', 'CAPD', 'Brasília', '#7a003c', '#ffffff', 54, 'Estádio Capital', 3],
    ['Ceilândia', 'CEID', 'Brasília', '#f5d100', '#111111', 52, 'Estádio Ceilândia', 5],
    ['Mixto', 'MIXM', 'Cuiabá', '#0d80bf', '#ffffff', 50, 'Estádio Mixto', 7],
    ['Operário', 'OPEM', 'Cuiabá', '#003aaf', '#ffffff', 48, 'Estádio Operário', 9],
    ['União', 'UNIM', 'Cuiabá', '#e30613', '#ffffff', 46, 'Estádio União', 11],
    ['Goiatuba', 'GOIG', 'Goiânia', '#006437', '#ffffff', 44, 'Estádio Goiatuba', 13],
    ['Trem', 'TREA', 'Macapá', '#111111', '#f5d100', 54, 'Estádio Trem', 15],
    ['Oratório', 'ORAA', 'Macapá', '#7a003c', '#ffffff', 52, 'Estádio Oratório', 17],
    ['Tuna Luso', 'TUNP', 'Belém', '#f5d100', '#111111', 50, 'Estádio Tuna Luso', 19],
    ['Águia de Marabá', 'ÁGUP', 'Belém', '#0d80bf', '#ffffff', 48, 'Estádio Águia de Marabá', 3],
    ['Tocantinópolis', 'TOCT', 'Araguaína', '#003aaf', '#ffffff', 46, 'Estádio Tocantinópolis', 5],
    ['Imperatriz', 'IMPM', 'São Luís', '#e30613', '#ffffff', 44, 'Estádio Imperatriz', 7],
    ['Sampaio Corrêa', 'SAMM', 'São Luís', '#006437', '#ffffff', 54, 'Estádio Sampaio Corrêa', 9],
    ['Moto Club', 'MOTM', 'São Luís', '#111111', '#f5d100', 52, 'Estádio Moto Club', 11],
    ['IAPE', 'IAPM', 'São Luís', '#7a003c', '#ffffff', 50, 'Estádio IAPE', 13],
    ['Maracanã', 'MARC', 'Fortaleza', '#f5d100', '#111111', 48, 'Estádio Maracanã', 15],
    ['Iguatu', 'IGUC', 'Fortaleza', '#0d80bf', '#ffffff', 46, 'Estádio Iguatu', 17],
    ['Parnahyba', 'PARP', 'Teresina', '#003aaf', '#ffffff', 44, 'Estádio Parnahyba', 19],
    ['Ferroviário', 'FERC', 'Fortaleza', '#e30613', '#ffffff', 54, 'Estádio Ferroviário', 3],
    ['Tirol', 'TIRC', 'Fortaleza', '#006437', '#ffffff', 52, 'Estádio Tirol', 5],
    ['Atlético-CE', 'ATLC', 'Fortaleza', '#111111', '#f5d100', 50, 'Estádio Atlético-CE', 7],
    ['Altos', 'ALTP', 'Teresina', '#7a003c', '#ffffff', 48, 'Estádio Altos', 9],
    ['Piauí', 'PIAP', 'Teresina', '#f5d100', '#111111', 46, 'Estádio Piauí', 11],
    ['Fluminense-PI', 'FLUP', 'Teresina', '#0d80bf', '#ffffff', 44, 'Estádio Fluminense-PI', 13],
    ['ABC', 'ABCR', 'Natal', '#003aaf', '#ffffff', 54, 'Estádio ABC', 15],
    ['América-RN', 'AMÉR', 'Natal', '#e30613', '#ffffff', 52, 'Estádio América-RN', 17],
    ['Laguna', 'LAGR', 'Natal', '#006437', '#ffffff', 50, 'Estádio Laguna', 19],
    ['Sousa', 'SOUP', 'João Pessoa', '#111111', '#f5d100', 48, 'Estádio Sousa', 3],
    ['Maguary', 'MAGP', 'Recife', '#7a003c', '#ffffff', 46, 'Estádio Maguary', 5],
    ['Central', 'CENP', 'Recife', '#f5d100', '#111111', 44, 'Estádio Central', 7],
    ['Retrô', 'RETP', 'Recife', '#0d80bf', '#ffffff', 54, 'Estádio Retrô', 9],
    ['Decisão', 'DECP', 'Recife', '#003aaf', '#ffffff', 52, 'Estádio Decisão', 11],
    ['Serra Branca', 'SERP', 'João Pessoa', '#e30613', '#ffffff', 50, 'Estádio Serra Branca', 13],
    ['Treze', 'TREP', 'João Pessoa', '#006437', '#ffffff', 48, 'Estádio Treze', 15],
    ['Lagarto', 'LAGS', 'Aracaju', '#111111', '#f5d100', 46, 'Estádio Lagarto', 17],
    ['Sergipe', 'SERS', 'Aracaju', '#7a003c', '#ffffff', 44, 'Estádio Sergipe', 19],
    ['ASA', 'ASAA', 'Maceió', '#f5d100', '#111111', 54, 'Estádio ASA', 3],
    ['CSA', 'CSAA', 'Maceió', '#0d80bf', '#ffffff', 52, 'Estádio CSA', 5],
    ['CSE', 'CSEA', 'Maceió', '#003aaf', '#ffffff', 50, 'Estádio CSE', 7],
    ['Jacuipense', 'JACB', 'Salvador', '#e30613', '#ffffff', 48, 'Estádio Jacuipense', 9],
    ['Atlético-BA', 'ATLB', 'Salvador', '#006437', '#ffffff', 46, 'Estádio Atlético-BA', 11],
    ['Juazeirense', 'JUAB', 'Salvador', '#111111', '#f5d100', 44, 'Estádio Juazeirense', 13],
    ['Uberlândia', 'UBEM', 'Uberlândia', '#7a003c', '#ffffff', 54, 'Estádio Uberlândia', 15],
    ['Betim', 'BETM', 'Uberlândia', '#f5d100', '#111111', 52, 'Estádio Betim', 17],
    ['CRAC', 'CRAG', 'Goiânia', '#0d80bf', '#ffffff', 50, 'Estádio CRAC', 19],
    ['ABECAT', 'ABEG', 'Goiânia', '#003aaf', '#ffffff', 48, 'Estádio ABECAT', 3],
    ['Operário-MS', 'OPEM', 'Campo Grande', '#e30613', '#ffffff', 46, 'Estádio Operário-MS', 5],
    ['Ivinhema', 'IVIM', 'Campo Grande', '#006437', '#ffffff', 44, 'Estádio Ivinhema', 7],
    ['Porto', 'PORB', 'Salvador', '#111111', '#f5d100', 54, 'Estádio Porto', 9],
    ['Rio Branco', 'RIOE', 'Vitória', '#7a003c', '#ffffff', 52, 'Estádio Rio Branco', 11],
    ['Vitória-ES', 'VITE', 'Vitória', '#f5d100', '#111111', 50, 'Estádio Vitória-ES', 13],
    ['Real Noroeste', 'REAE', 'Vitória', '#0d80bf', '#ffffff', 48, 'Estádio Real Noroeste', 15],
    ['Tombense', 'TOMM', 'Uberlândia', '#003aaf', '#ffffff', 46, 'Estádio Tombense', 17],
    ['Democrata GV', 'DEMM', 'Uberlândia', '#e30613', '#ffffff', 44, 'Estádio Democrata GV', 19],
    ['Madureira', 'MADR', 'Rio de Janeiro', '#006437', '#ffffff', 54, 'Estádio Madureira', 3],
    ['Portuguesa-RJ', 'PORR', 'Rio de Janeiro', '#111111', '#f5d100', 52, 'Estádio Portuguesa-RJ', 5],
    ['America-RJ', 'AMER', 'Rio de Janeiro', '#7a003c', '#ffffff', 50, 'Estádio America-RJ', 7],
    ['Portuguesa', 'PORS', 'São Paulo', '#f5d100', '#111111', 48, 'Estádio Portuguesa', 9],
    ['Água Santa', 'ÁGUS', 'São Paulo', '#0d80bf', '#ffffff', 46, 'Estádio Água Santa', 11],
    ['Pouso Alegre', 'POUM', 'Uberlândia', '#003aaf', '#ffffff', 44, 'Estádio Pouso Alegre', 13],
    ['Nova Iguaçu', 'NOVR', 'Rio de Janeiro', '#e30613', '#ffffff', 54, 'Estádio Nova Iguaçu', 15],
    ['Sampaio Corrêa-RJ', 'SAMR', 'Rio de Janeiro', '#006437', '#ffffff', 52, 'Estádio Sampaio Corrêa-RJ', 17],
    ['Maricá', 'MARR', 'Rio de Janeiro', '#111111', '#f5d100', 50, 'Estádio Maricá', 19],
    ['XV de Piracicaba', 'XVDS', 'São Paulo', '#7a003c', '#ffffff', 48, 'Estádio XV de Piracicaba', 3],
    ['Noroeste', 'NORS', 'São Paulo', '#f5d100', '#111111', 46, 'Estádio Noroeste', 5],
    ['Velo Clube', 'VELS', 'São Paulo', '#0d80bf', '#ffffff', 44, 'Estádio Velo Clube', 7],
    ['Cianorte', 'CIAP', 'Curitiba', '#003aaf', '#ffffff', 54, 'Estádio Cianorte', 9],
    ['FC Cascavel', 'FCCP', 'Curitiba', '#e30613', '#ffffff', 52, 'Estádio FC Cascavel', 11],
    ['Santa Catarina', 'SANS', 'Joinville', '#006437', '#ffffff', 50, 'Estádio Santa Catarina', 13],
    ['Joinville', 'JOIS', 'Joinville', '#111111', '#f5d100', 48, 'Estádio Joinville', 15],
    ['Guarany de Bagé', 'GUAR', 'Porto Alegre', '#7a003c', '#ffffff', 46, 'Estádio Guarany de Bagé', 17],
    ['São Luiz', 'SÃOR', 'Porto Alegre', '#f5d100', '#111111', 44, 'Estádio São Luiz', 19],
    ['Blumenau', 'BLUS', 'Joinville', '#0d80bf', '#ffffff', 54, 'Estádio Blumenau', 3],
    ['Marcílio Dias', 'MARS', 'Joinville', '#003aaf', '#ffffff', 52, 'Estádio Marcílio Dias', 5],
    ['São Joseense', 'SÃOP', 'Curitiba', '#e30613', '#ffffff', 50, 'Estádio São Joseense', 7],
    ['Azuriz', 'AZUP', 'Curitiba', '#006437', '#ffffff', 48, 'Estádio Azuriz', 9],
    ['São José', 'SÃOR', 'Porto Alegre', '#111111', '#f5d100', 46, 'Estádio São José', 11],
    ['Brasil de Pelotas', 'BRAR', 'Porto Alegre', '#7a003c', '#ffffff', 44, 'Estádio Brasil de Pelotas', 13],
  ],
  ar1: [
    ['Boca Juniors', 'BOC', 'Buenos Aires', '#003aaf', '#f5d100', 90, 'La Bombonera', 54],
    ['River Plate', 'RIV', 'Buenos Aires', '#e30613', '#ffffff', 90, 'Monumental de Núñez', 84],
    ['Racing', 'RAC', 'Avellaneda', '#0d80bf', '#ffffff', 80, 'El Cilindro', 55],
    ['Independiente', 'IND', 'Avellaneda', '#e30613', '#ffffff', 80, 'Libertadores de América', 48],
    ['San Lorenzo', 'SLO', 'Buenos Aires', '#5b2a86', '#e30613', 78, 'Nuevo Gasómetro', 47],
    ['Estudiantes', 'EST', 'La Plata', '#e30613', '#ffffff', 78, 'Jorge Luis Hirschi', 30],
    ['Vélez Sarsfield', 'VEL', 'Buenos Aires', '#003aaf', '#ffffff', 77, 'José Amalfitani', 49],
    ["Newell's Old Boys", 'NOB', 'Rosario', '#e30613', '#111111', 74, 'Marcelo Bielsa', 42],
    ['Rosario Central', 'ROS', 'Rosario', '#003aaf', '#f5d100', 74, 'Gigante de Arroyito', 41],
    ['Talleres', 'TAL', 'Córdoba', '#003aaf', '#ffffff', 74, 'Mario Alberto Kempes', 57],
    ['Lanús', 'LAN', 'Lanús', '#7a003c', '#ffffff', 72, 'La Fortaleza', 47],
    ['Banfield', 'BAN', 'Banfield', '#006437', '#ffffff', 68, 'Florencio Sola', 34],
    ['Defensa y Justicia', 'DYJ', 'Florencio Varela', '#006437', '#f5d100', 70, 'Norberto Tomaghello', 12],
    ['Argentinos Juniors', 'ARG', 'Buenos Aires', '#e30613', '#ffffff', 69, 'Diego Armando Maradona', 25],
    ['Huracán', 'HUR', 'Buenos Aires', '#e30613', '#ffffff', 69, 'Tomás Adolfo Ducó', 48],
    ['Gimnasia LP', 'GIM', 'La Plata', '#003aaf', '#ffffff', 68, 'Juan Carmelo Zerillo', 24],
    ['Platense', 'PLA', 'Vicente López', '#7a003c', '#ffffff', 63, 'Ciudad de Vicente López', 28],
    ['Tigre', 'TIG', 'Victoria', '#003aaf', '#e30613', 64, 'José Dellagiovanna', 26],
    ['Belgrano', 'BEL', 'Córdoba', '#0d80bf', '#111111', 67, 'Julio César Villagra', 30],
    ['Instituto', 'INS', 'Córdoba', '#e30613', '#ffffff', 62, 'Juan Domingo Perón', 26],
  ],
  en1: [
    ['Manchester City', 'MCI', 'Manchester', '#6cabdd', '#ffffff', 95, 'Etihad Stadium', 53],
    ['Liverpool', 'LIV', 'Liverpool', '#c1121f', '#ffffff', 93, 'Anfield', 61],
    ['Arsenal', 'ARS', 'Londres', '#e30613', '#ffffff', 92, 'Emirates Stadium', 60],
    ['Manchester United', 'MUN', 'Manchester', '#c1121f', '#f5d100', 90, 'Old Trafford', 74],
    ['Chelsea', 'CHE', 'Londres', '#003aaf', '#ffffff', 89, 'Stamford Bridge', 40],
    ['Tottenham Hotspur', 'TOT', 'Londres', '#ffffff', '#111111', 87, 'Tottenham Hotspur Stadium', 62],
    ['Newcastle United', 'NEW', 'Newcastle', '#111111', '#ffffff', 84, "St James' Park", 52],
    ['Aston Villa', 'AVL', 'Birmingham', '#5b2a86', '#7ab8e0', 83, 'Villa Park', 42],
    ['West Ham United', 'WHU', 'Londres', '#7a003c', '#7ab8e0', 80, 'London Stadium', 62],
    ['Brighton', 'BHA', 'Brighton', '#003aaf', '#ffffff', 79, 'Amex Stadium', 31],
    ['Everton', 'EVE', 'Liverpool', '#003aaf', '#ffffff', 79, 'Goodison Park', 39],
    ['Crystal Palace', 'CRY', 'Londres', '#003aaf', '#e30613', 76, 'Selhurst Park', 25],
    ['Fulham', 'FUL', 'Londres', '#ffffff', '#e30613', 75, 'Craven Cottage', 24],
    ['Wolverhampton', 'WOL', 'Wolverhampton', '#f5a800', '#111111', 75, 'Molineux Stadium', 31],
    ['Brentford', 'BRE', 'Londres', '#e30613', '#111111', 74, 'Gtech Community Stadium', 17],
    ['Bournemouth', 'BOU', 'Bournemouth', '#e30613', '#111111', 73, 'Vitality Stadium', 11],
    ['Nottingham Forest', 'NFO', 'Nottingham', '#c1121f', '#ffffff', 75, 'City Ground', 30],
    ['Leicester City', 'LEI', 'Leicester', '#003aaf', '#f5d100', 74, 'King Power Stadium', 32],
    ['Leeds United', 'LEE', 'Leeds', '#f5d100', '#003aaf', 74, 'Elland Road', 37],
    ['Sunderland', 'SUN', 'Sunderland', '#e30613', '#ffffff', 73, 'Stadium of Light', 48],
  ],
  es1: [
    ['Real Madrid', 'RMA', 'Madri', '#ffffff', '#f5d100', 97, 'Santiago Bernabéu', 81],
    ['Barcelona', 'BAR', 'Barcelona', '#a50044', '#003aaf', 95, 'Camp Nou', 99],
    ['Atlético de Madrid', 'ATM', 'Madri', '#e30613', '#ffffff', 91, 'Cívitas Metropolitano', 70],
    ['Sevilla', 'SEV', 'Sevilha', '#e30613', '#ffffff', 84, 'Ramón Sánchez-Pizjuán', 43],
    ['Real Betis', 'BET', 'Sevilha', '#006437', '#ffffff', 80, 'Benito Villamarín', 60],
    ['Villarreal', 'VIL', 'Villarreal', '#f5d100', '#003aaf', 82, 'La Cerámica', 23],
    ['Athletic Club', 'ATH', 'Bilbao', '#e30613', '#ffffff', 82, 'San Mamés', 53],
    ['Real Sociedad', 'RSO', 'San Sebastián', '#003aaf', '#ffffff', 81, 'Reale Arena', 39],
    ['Valencia', 'VAL', 'Valência', '#f5d100', '#111111', 79, 'Mestalla', 49],
    ['Celta de Vigo', 'CEL', 'Vigo', '#7ab8e0', '#ffffff', 75, 'Balaídos', 29],
    ['Getafe', 'GET', 'Getafe', '#003aaf', '#ffffff', 72, 'Coliseum', 16],
    ['Osasuna', 'OSA', 'Pamplona', '#e30613', '#003aaf', 73, 'El Sadar', 23],
    ['Girona', 'GIR', 'Girona', '#e30613', '#ffffff', 76, 'Montilivi', 14],
    ['Rayo Vallecano', 'RAY', 'Madri', '#e30613', '#ffffff', 70, 'Vallecas', 14],
    ['Mallorca', 'MAL', 'Palma', '#e30613', '#f5d100', 70, 'Son Moix', 23],
    ['Alavés', 'ALA', 'Vitoria-Gasteiz', '#003aaf', '#ffffff', 69, 'Mendizorroza', 19],
    ['Espanyol', 'ESP', 'Barcelona', '#003aaf', '#ffffff', 71, 'RCDE Stadium', 40],
    ['Levante', 'LEV', 'Valência', '#e30613', '#003aaf', 67, 'Ciutat de València', 26],
    ['Real Oviedo', 'OVI', 'Oviedo', '#003aaf', '#ffffff', 65, 'Carlos Tartiere', 30],
    ['Elche', 'ELC', 'Elche', '#006437', '#ffffff', 66, 'Martínez Valero', 33],
  ],
  it1: [
    ['Inter', 'INT', 'Milão', '#003aaf', '#111111', 92, 'San Siro', 75],
    ['Milan', 'MIL', 'Milão', '#e30613', '#111111', 91, 'San Siro', 75],
    ['Juventus', 'JUV', 'Turim', '#111111', '#ffffff', 91, 'Allianz Stadium', 41],
    ['Napoli', 'NAP', 'Nápoles', '#0d80bf', '#ffffff', 89, 'Diego Armando Maradona', 54],
    ['Roma', 'ROM', 'Roma', '#8e1f2f', '#f5a800', 86, 'Estádio Olímpico', 70],
    ['Lazio', 'LAZ', 'Roma', '#7ab8e0', '#ffffff', 84, 'Estádio Olímpico', 70],
    ['Atalanta', 'ATA', 'Bérgamo', '#003aaf', '#111111', 85, 'Gewiss Stadium', 25],
    ['Fiorentina', 'FIO', 'Florença', '#5b2a86', '#ffffff', 81, 'Artemio Franchi', 43],
    ['Bologna', 'BOL', 'Bolonha', '#8e1f2f', '#003aaf', 78, "Renato Dall'Ara", 36],
    ['Torino', 'TOR', 'Turim', '#7a003c', '#f5d100', 74, 'Olímpico Grande Torino', 27],
    ['Genoa', 'GEN', 'Gênova', '#e30613', '#003aaf', 73, 'Luigi Ferraris', 33],
    ['Sampdoria', 'SMP', 'Gênova', '#003aaf', '#e30613', 72, 'Luigi Ferraris', 33],
    ['Udinese', 'UDI', 'Údine', '#111111', '#ffffff', 71, 'Bluenergy Stadium', 25],
    ['Monza', 'MON', 'Monza', '#e30613', '#ffffff', 70, 'U-Power Stadium', 18],
    ['Lecce', 'LEC', 'Lecce', '#f5d100', '#e30613', 68, 'Via del Mare', 31],
    ['Cagliari', 'CAG', 'Cagliari', '#8e1f2f', '#003aaf', 69, 'Unipol Domus', 16],
    ['Hellas Verona', 'VER', 'Verona', '#f5d100', '#003aaf', 69, "Marcantonio Bentegodi", 39],
    ['Parma', 'PAR', 'Parma', '#f5d100', '#003aaf', 71, 'Ennio Tardini', 27],
    ['Como', 'COM', 'Como', '#003aaf', '#ffffff', 68, 'Giuseppe Sinigaglia', 13],
    ['Sassuolo', 'SAS', 'Sassuolo', '#006437', '#111111', 70, 'Mapei Stadium', 21],
  ],
  de1: [
    ['Bayern München', 'BAY', 'Munique', '#c1121f', '#ffffff', 96, 'Allianz Arena', 75],
    ['Borussia Dortmund', 'BVB', 'Dortmund', '#f5d100', '#111111', 90, 'Signal Iduna Park', 81],
    ['Bayer Leverkusen', 'B04', 'Leverkusen', '#e30613', '#111111', 87, 'BayArena', 30],
    ['RB Leipzig', 'RBL', 'Leipzig', '#e30613', '#ffffff', 86, 'Red Bull Arena', 47],
    ['Eintracht Frankfurt', 'SGE', 'Frankfurt', '#e30613', '#111111', 81, 'Deutsche Bank Park', 51],
    ['VfL Wolfsburg', 'WOB', 'Wolfsburg', '#006437', '#ffffff', 76, 'Volkswagen Arena', 30],
    ["Borussia M'gladbach", 'BMG', "Mönchengladbach", '#006437', '#111111', 76, 'Borussia-Park', 54],
    ['VfB Stuttgart', 'VFB', 'Stuttgart', '#e30613', '#ffffff', 79, 'MHPArena', 60],
    ['SC Freiburg', 'SCF', 'Friburgo', '#e30613', '#ffffff', 76, 'Europa-Park Stadion', 34],
    ['Union Berlin', 'FCU', 'Berlim', '#e30613', '#f5d100', 75, 'An der Alten Försterei', 22],
    ['Werder Bremen', 'SVW', 'Bremen', '#006437', '#ffffff', 74, 'Weserstadion', 42],
    ['Mainz 05', 'M05', 'Mainz', '#e30613', '#ffffff', 71, 'Mewa Arena', 33],
    ['Hoffenheim', 'TSG', 'Sinsheim', '#003aaf', '#ffffff', 71, 'PreZero Arena', 30],
    ['FC Köln', 'KOE', 'Colônia', '#e30613', '#ffffff', 72, 'RheinEnergieStadion', 50],
    ['Hamburger SV', 'HSV', 'Hamburgo', '#003aaf', '#ffffff', 74, 'Volksparkstadion', 57],
    ['FC St. Pauli', 'STP', 'Hamburgo', '#6b4423', '#ffffff', 67, 'Millerntor-Stadion', 29],
    ['FC Augsburg', 'FCA', 'Augsburg', '#e30613', '#006437', 69, 'WWK Arena', 30],
    ['Heidenheim', 'HEI', 'Heidenheim', '#e30613', '#003aaf', 64, 'Voith-Arena', 15],
  ],
  fr1: [
    ['Paris Saint-Germain', 'PSG', 'Paris', '#003aaf', '#e30613', 93, 'Parc des Princes', 48],
    ['Olympique Marseille', 'OM', 'Marselha', '#7ab8e0', '#ffffff', 85, 'Orange Vélodrome', 67],
    ['AS Monaco', 'ASM', 'Mônaco', '#e30613', '#ffffff', 84, 'Stade Louis-II', 18],
    ['Lille', 'LIL', 'Lille', '#e30613', '#003aaf', 82, 'Stade Pierre-Mauroy', 50],
    ['Lyon', 'OL', 'Lyon', '#ffffff', '#e30613', 82, 'Groupama Stadium', 59],
    ['Nice', 'NCE', 'Nice', '#e30613', '#111111', 76, 'Allianz Riviera', 36],
    ['Rennes', 'REN', 'Rennes', '#e30613', '#111111', 76, 'Roazhon Park', 29],
    ['Lens', 'RCL', 'Lens', '#e30613', '#f5d100', 77, 'Stade Bollaert-Delelis', 38],
    ['Strasbourg', 'STR', 'Estrasburgo', '#003aaf', '#ffffff', 73, 'Stade de la Meinau', 26],
    ['Nantes', 'NAN', 'Nantes', '#f5d100', '#006437', 70, 'Stade de la Beaujoire', 35],
    ['Toulouse', 'TOU', 'Toulouse', '#5b2a86', '#ffffff', 71, 'Stadium de Toulouse', 33],
    ['Montpellier', 'MON', 'Montpellier', '#003aaf', '#e30613', 68, 'Stade de la Mosson', 32],
    ['Brest', 'BRE', 'Brest', '#e30613', '#ffffff', 70, 'Stade Francis-Le Blé', 15],
    ['Reims', 'REI', 'Reims', '#e30613', '#ffffff', 69, 'Stade Auguste-Delaune', 21],
    ['Auxerre', 'AUX', 'Auxerre', '#003aaf', '#ffffff', 68, "Stade de l'Abbé-Deschamps", 21],
    ['Angers', 'ANG', 'Angers', '#111111', '#ffffff', 64, 'Stade Raymond Kopa', 18],
    ['Le Havre', 'HAC', 'Le Havre', '#003aaf', '#7ab8e0', 64, 'Stade Océane', 25],
    ['Lorient', 'LOR', 'Lorient', '#f5a800', '#111111', 66, 'Stade du Moustoir', 18],
  ],
  pt1: [
    ['Benfica', 'BEN', 'Lisboa', '#e30613', '#ffffff', 89, 'Estádio da Luz', 64],
    ['Porto', 'POR', 'Porto', '#003aaf', '#ffffff', 88, 'Estádio do Dragão', 50],
    ['Sporting CP', 'SCP', 'Lisboa', '#006437', '#ffffff', 87, 'Estádio José Alvalade', 50],
    ['Braga', 'BRA', 'Braga', '#e30613', '#ffffff', 79, 'Estádio Municipal de Braga', 30],
    ['Vitória Guimarães', 'VSC', 'Guimarães', '#111111', '#ffffff', 73, 'Estádio D. Afonso Henriques', 30],
    ['Boavista', 'BOA', 'Porto', '#111111', '#ffffff', 67, 'Estádio do Bessa', 28],
    ['Gil Vicente', 'GIL', 'Barcelos', '#e30613', '#003aaf', 64, 'Estádio Cidade de Barcelos', 12],
    ['Famalicão', 'FAM', 'Vila Nova de Famalicão', '#003aaf', '#ffffff', 66, 'Estádio Municipal 22 de Junho', 5],
    ['Estoril', 'EST', 'Estoril', '#f5d100', '#003aaf', 64, 'Estádio António Coimbra da Mota', 8],
    ['Casa Pia', 'CAS', 'Lisboa', '#111111', '#ffffff', 63, 'Estádio Municipal de Rio Maior', 7],
    ['Rio Ave', 'RIO', 'Vila do Conde', '#006437', '#ffffff', 65, 'Estádio dos Arcos', 9],
    ['Arouca', 'ARO', 'Arouca', '#f5d100', '#003aaf', 63, 'Estádio Municipal de Arouca', 5],
    ['Moreirense', 'MOR', 'Moreira de Cónegos', '#006437', '#ffffff', 62, 'Parque Joaquim de Almeida Freitas', 6],
    ['Nacional', 'NAC', 'Funchal', '#111111', '#ffffff', 62, 'Estádio da Madeira', 5],
    ['Santa Clara', 'STC', 'Ponta Delgada', '#e30613', '#ffffff', 63, 'Estádio de São Miguel', 13],
    ['Farense', 'FAR', 'Faro', '#111111', '#f5d100', 60, 'Estádio de São Luís', 7],
    ['Estrela Amadora', 'EAM', 'Amadora', '#006437', '#e30613', 59, 'Estádio José Gomes', 9],
    ['AVS', 'AVS', 'Vila das Aves', '#e30613', '#f5d100', 58, 'Estádio do CD Aves', 8],
  ],
  nl1: [
    ['Ajax', 'AJA', 'Amsterdã', '#e30613', '#ffffff', 88, 'Johan Cruyff Arena', 55],
    ['PSV Eindhoven', 'PSV', 'Eindhoven', '#e30613', '#ffffff', 87, 'Philips Stadion', 35],
    ['Feyenoord', 'FEY', 'Roterdã', '#e30613', '#111111', 86, 'De Kuip', 51],
    ['AZ Alkmaar', 'AZ', 'Alkmaar', '#e30613', '#111111', 79, 'AFAS Stadion', 19],
    ['FC Twente', 'TWE', 'Enschede', '#e30613', '#ffffff', 75, 'De Grolsch Veste', 30],
    ['Utrecht', 'UTR', 'Utrecht', '#e30613', '#ffffff', 71, 'Stadion Galgenwaard', 23],
    ['Heerenveen', 'HEE', 'Heerenveen', '#003aaf', '#ffffff', 68, 'Abe Lenstra Stadion', 27],
    ['NEC Nijmegen', 'NEC', 'Nijmegen', '#e30613', '#006437', 68, 'Goffertstadion', 12],
    ['Sparta Rotterdam', 'SPA', 'Roterdã', '#e30613', '#ffffff', 67, 'Sparta Stadion Het Kasteel', 11],
    ['Go Ahead Eagles', 'GAE', 'Deventer', '#e30613', '#f5d100', 66, 'De Adelaarshorst', 10],
    ['Groningen', 'GRO', 'Groningen', '#006437', '#ffffff', 67, 'Euroborg', 22],
    ['Willem II', 'WIL', 'Tilburg', '#e30613', '#003aaf', 66, 'Koning Willem II Stadion', 14],
    ['Fortuna Sittard', 'FOR', 'Sittard', '#f5d100', '#006437', 63, 'Fortuna Sittard Stadion', 12],
    ['Almere City', 'ALM', 'Almere', '#e30613', '#111111', 62, 'Yanmar Stadion', 4],
    ['NAC Breda', 'NAC', 'Breda', '#f5d100', '#111111', 63, 'Rat Verlegh Stadion', 19],
    ['PEC Zwolle', 'ZWO', 'Zwolle', '#003aaf', '#ffffff', 64, 'MAC³PARK Stadion', 14],
    ['Heracles', 'HER', 'Almelo', '#111111', '#ffffff', 62, 'Erve Asito', 12],
    ['Excelsior', 'EXC', 'Roterdã', '#e30613', '#111111', 61, 'Van Donge & De Roo Stadion', 4],
  ],
};

// -------------------- NOMES DE JOGADORES (geração procedural) --------------------
export const NAME_POOLS = {
  br: {
    first: ['Gabriel', 'Lucas', 'Matheus', 'Pedro', 'Vinícius', 'Rafael', 'Bruno', 'Thiago', 'Felipe', 'Rodrigo', 'Gustavo', 'Diego', 'André', 'Caio', 'Eduardo', 'Fernando', 'Guilherme', 'Henrique', 'Igor', 'João', 'Kauã', 'Leonardo', 'Marcos', 'Nathan', 'Otávio', 'Paulo', 'Renan', 'Samuel', 'Victor', 'Wesley', 'Yuri', 'Arthur', 'Danilo', 'Everton', 'Fábio', 'Hugo', 'Jean', 'Murilo', 'Nicolas', 'Pablo', 'Ricardo', 'Sérgio', 'Talles', 'Willian', 'Adriano', 'Alex', 'Antony', 'Breno', 'Carlos', 'Daniel', 'Ederson', 'Fabinho', 'Gerson', 'Luan', 'Marlon', 'Oscar', 'Patrick', 'Richarlison', 'Savio', 'Tetê', 'Vanderson', 'Zé'],
    firstF: ['Ana', 'Beatriz', 'Camila', 'Débora', 'Elena', 'Fernanda', 'Gabriela', 'Helena', 'Isabela', 'Júlia', 'Larissa', 'Lívia', 'Luana', 'Mariana', 'Natália', 'Olívia', 'Patrícia', 'Rafaela', 'Sofia', 'Tainá', 'Valentina', 'Yasmin', 'Amanda', 'Bruna', 'Carla', 'Duda', 'Elisa', 'Flávia', 'Giovana', 'Ingrid', 'Joana', 'Karina', 'Letícia', 'Maitê', 'Nicole', 'Paula', 'Raquel', 'Sabrina', 'Tatiane', 'Vitória', 'Aline', 'Bianca', 'Carol', 'Daiane', 'Érica', 'Fabiana', 'Gisele', 'Heloísa', 'Isadora', 'Jéssica'],
    last: ['Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Alves', 'Pereira', 'Lima', 'Gomes', 'Costa', 'Ribeiro', 'Martins', 'Carvalho', 'Rocha', 'Almeida', 'Nascimento', 'Araújo', 'Melo', 'Barbosa', 'Cardoso', 'Correia', 'Dias', 'Teixeira', 'Fernandes', 'Freitas', 'Moreira', 'Nogueira', 'Pinto', 'Ramos', 'Cavalcante', 'Duarte', 'Farias', 'Macedo', 'Moraes', 'Nunes', 'Peixoto', 'Reis', 'Sales', 'Vieira', 'Andrade', 'Batista', 'Campos', 'Cunha', 'Figueiredo', 'Lopes', 'Miranda', 'Monteiro', 'Pires', 'Tavares', 'Viana', 'Assis', 'Borges', 'Castro', 'Dantas', 'Esteves', 'Fonseca', 'Guimarães', 'Leite', 'Maia', 'Neves', 'Paiva', 'Queiroz', 'Siqueira', 'Toledo', 'Vasconcelos', 'Braga', 'Aguiar', 'Barros', 'Coelho'],
  },
  hisp: {
    first: ['Alejandro', 'Bruno', 'Carlos', 'Damián', 'Diego', 'Emiliano', 'Enzo', 'Facundo', 'Federico', 'Franco', 'Gonzalo', 'Ignacio', 'Joaquín', 'Julián', 'Lautaro', 'Lisandro', 'Luciano', 'Marcos', 'Mateo', 'Matías', 'Maximiliano', 'Nicolás', 'Pablo', 'Pedro', 'Santiago', 'Sebastián', 'Thiago', 'Tomás', 'Valentín', 'Exequiel', 'Agustín', 'Alexis', 'Andrés', 'Ángel', 'Cristian', 'Ezequiel', 'Germán', 'Hernán', 'Iván', 'Javier', 'Kevin', 'Leandro', 'Manuel', 'Marcelo', 'Mauricio', 'Nahuel', 'Óscar', 'Ramiro', 'Rodrigo', 'Rubén'],
    firstF: ['Sofía', 'Valentina', 'Camila', 'Luciana', 'Martina', 'Julieta', 'Florencia', 'Agustina', 'Milagros', 'Catalina', 'Isabella', 'Antonella', 'Renata', 'Josefina', 'Emilia', 'Victoria', 'Guadalupe', 'Abril', 'Morena', 'Malena', 'Delfina', 'Amparo', 'Lucía', 'Micaela', 'Rocío'],
    last: ['González', 'Rodríguez', 'Fernández', 'López', 'Martínez', 'Pérez', 'García', 'Romero', 'Sosa', 'Álvarez', 'Torres', 'Ruiz', 'Ramírez', 'Flores', 'Benítez', 'Acosta', 'Medina', 'Herrera', 'Suárez', 'Aguirre', 'Giménez', 'Pereyra', 'Rojas', 'Castillo', 'Vega', 'Campos', 'Fuentes', 'Cabrera', 'Morales', 'Navarro', 'Ortiz', 'Vargas', 'Castro', 'Paredes', 'Mercado', 'Quiroga', 'Figueroa', 'Palacios', 'Ledesma', 'Arce'],
  },
  en: {
    first: ['Jack', 'Harry', 'Oliver', 'George', 'Charlie', 'Jacob', 'Alfie', 'Leo', 'Oscar', 'Henry', 'Archie', 'Joshua', 'Ethan', 'Daniel', 'Samuel', 'James', 'William', 'Thomas', 'Benjamin', 'Lucas', 'Mason', 'Finley', 'Harrison', 'Jude', 'Cole', 'Declan', 'Phil', 'Bukayo', 'Marcus', 'Trent', 'Jordan', 'Aaron', 'Callum', 'Reece', 'Conor', 'Mason', 'Jarrod', 'Ivan', 'Ollie', 'Kobbie', 'Lewis', 'Curtis', 'Anthony', 'Dominic', 'Kieran', 'Ben', 'Luke'],
    firstF: ['Olivia', 'Amelia', 'Isla', 'Ava', 'Mia', 'Poppy', 'Freya', 'Grace', 'Sophie', 'Emily', 'Ella', 'Evie', 'Ruby', 'Lily', 'Chloe', 'Jessica', 'Charlotte', 'Harriet', 'Daisy', 'Maisie', 'Nancy', 'Darcie', 'Elsie', 'Phoebe', 'Imogen'],
    last: ['Smith', 'Jones', 'Williams', 'Taylor', 'Brown', 'Davies', 'Wilson', 'Evans', 'Thomas', 'Johnson', 'Roberts', 'Walker', 'Wright', 'Robinson', 'Thompson', 'Hughes', 'White', 'Edwards', 'Green', 'Hall', 'Lewis', 'Harris', 'Clarke', 'Patel', 'Jackson', 'Wood', 'Turner', 'Martin', 'Cooper', 'Hill', 'Ward', 'Morris', 'Moore', 'Clark', 'King', 'Baker', 'Young', 'Allen', 'Mitchell', 'Phillips', 'Campbell', 'Parker', 'Bell', 'Graham', 'Kelly', 'Howard', 'Rice', 'Foden', 'Palmer'],
  },
  it: {
    first: ['Alessandro', 'Andrea', 'Antonio', 'Carlo', 'Daniele', 'Davide', 'Domenico', 'Edoardo', 'Federico', 'Filippo', 'Francesco', 'Gabriele', 'Giacomo', 'Giorgio', 'Giovanni', 'Giuseppe', 'Lorenzo', 'Luca', 'Marco', 'Matteo', 'Mattia', 'Michele', 'Nicola', 'Riccardo', 'Salvatore', 'Simone', 'Stefano', 'Tommaso', 'Vincenzo', 'Alessio', 'Bruno', 'Claudio', 'Elia', 'Fabio', 'Gianluca', 'Ivan', 'Manuel', 'Massimo', 'Paolo', 'Pietro', 'Renato', 'Samuele', 'Umberto', 'Valerio'],
    firstF: ['Sofia', 'Giulia', 'Alessia', 'Chiara', 'Francesca', 'Martina', 'Giorgia', 'Anna', 'Elena', 'Sara', 'Giovanna', 'Beatrice', 'Ludovica', 'Bianca', 'Vittoria', 'Aurora', 'Rachele', 'Gaia', 'Emma', 'Matilde', 'Camilla', 'Noemi', 'Greta', 'Marta', 'Serena'],
    last: ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco', 'Bruno', 'Gallo', 'Conti', 'De Luca', 'Costa', 'Giordano', 'Mancini', 'Rizzo', 'Lombardi', 'Moretti', 'Barbieri', 'Fontana', 'Santoro', 'Mariani', 'Rinaldi', 'Caruso', 'Ferraro', 'Fabbri', 'Valentini', 'Basile', 'Serra', 'Vitale', 'Pellegrini', 'Bellini', 'Monti', 'Palumbo', 'Sorrentino', 'Leone', 'Marchetti', 'Battaglia', 'Neri', 'Franco', 'Martini', 'Ferretti', 'Parisi', 'Testa', 'Grassi', 'Riva', 'Caputo'],
  },
  de: {
    first: ['Ben', 'Finn', 'Jonas', 'Leon', 'Luca', 'Lukas', 'Maximilian', 'Moritz', 'Niklas', 'Noah', 'Paul', 'Philipp', 'Tim', 'Tom', 'Felix', 'Jan', 'Julian', 'Kai', 'Kevin', 'Marco', 'Marius', 'Nico', 'Sebastian', 'Simon', 'Timo', 'Tobias', 'Yannick', 'Dominik', 'Erik', 'Florian', 'Henrik', 'Jamal', 'Joshua', 'Karim', 'Leroy', 'Mats', 'Max', 'Robin', 'Serge', 'Sven', 'Thilo', 'Tony', 'Tristan', 'Wout', 'Sepp', 'Xaver', 'Malik', 'Emre', 'Antonio'],
    firstF: ['Emma', 'Hannah', 'Mia', 'Lea', 'Lena', 'Anna', 'Lina', 'Marie', 'Sophie', 'Emilia', 'Clara', 'Laura', 'Julia', 'Amelie', 'Katharina', 'Marlene', 'Frieda', 'Ida', 'Nora', 'Paula', 'Greta', 'Maja', 'Lotte', 'Alma', 'Ronja'],
    last: ['Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Hoffmann', 'Schulz', 'Koch', 'Bauer', 'Richter', 'Klein', 'Wolf', 'Neumann', 'Schwarz', 'Zimmermann', 'Braun', 'Krüger', 'Hartmann', 'Lange', 'Schmitt', 'Werner', 'Krause', 'Meier', 'Lehmann', 'Schmid', 'Schulze', 'Maier', 'Köhler', 'Herrmann', 'Walter', 'König', 'Mayer', 'Huber', 'Kaiser', 'Fuchs', 'Peters', 'Lang', 'Scholz', 'Brandt', 'Haas', 'Vogel', 'Jung', 'Hahn', 'Keller', 'Busch', 'Berger', 'Kramer'],
  },
  fr: {
    first: ['Adrien', 'Alexandre', 'Antoine', 'Aurélien', 'Benjamin', 'Brice', 'Clément', 'Corentin', 'Dimitri', 'Enzo', 'Florian', 'Hugo', 'Jordan', 'Jules', 'Kylian', 'Léo', 'Loïc', 'Louis', 'Lucas', 'Mathis', 'Maxence', 'Moussa', 'Nabil', 'Nathan', 'Nicolas', 'Olivier', 'Paul', 'Pierre', 'Quentin', 'Randal', 'Romain', 'Samuel', 'Sofiane', 'Théo', 'Thomas', 'Valentin', 'Wissam', 'Yacine', 'Boubacar', 'Dayot', 'Gautier', 'Ismaël', 'Jonathan', 'Kingsley', 'Leny', 'Maghnes', 'Youssouf', 'Warren'],
    firstF: ['Louise', 'Emma', 'Jade', 'Léa', 'Manon', 'Chloé', 'Camille', 'Sarah', 'Inès', 'Lina', 'Nina', 'Juliette', 'Zoé', 'Anaïs', 'Margaux', 'Clara', 'Alice', 'Jeanne', 'Romane', 'Élise', 'Ambre', 'Maëlys', 'Victoire', 'Constance', 'Apolline'],
    last: ['Martin', 'Bernard', 'Dubois', 'Thomas', 'Robert', 'Richard', 'Petit', 'Durand', 'Leroy', 'Moreau', 'Simon', 'Laurent', 'Lefèvre', 'Michel', 'David', 'Bertrand', 'Roux', 'Vincent', 'Fournier', 'Morel', 'Girard', 'André', 'Lefebvre', 'Mercier', 'Dupont', 'Lambert', 'Bonnet', 'Fontaine', 'Rousseau', 'Chevalier', 'Robin', 'Barbier', 'Gauthier', 'Perrin', 'Charpentier', 'Renard', 'Moulin', 'Collet', 'Benoit', 'Gros', 'Henry', 'Masson', 'Marchand', 'Duval', 'Denis', 'Dumont', 'Marie', 'Noël', 'Perrot', 'Camara'],
  },
};

// Treinadores (gerados)
export const COACH_NAMES = {
  br: ['Manoel Ferreira','Rogério Alencar','Tite Ramalho','Dorival Prates','Abel Nogueira','Fernando Diniz Moreira','Renato Gaúcho Lima','Vanderlei Rosa','Cuca Mendes','Felipão Braga','Muricy Costa','Carille Souza','Odair Hellmann','Silvinho Castro','Zé Ricardo Pires'],
  hisp: ['Marcelo Bielsa Ortega','Diego Simeone Vera','Jorge Sampaoli Ruiz','Marcelo Gallardo Peralta','Ramón Díaz Torres','Hernán Crespo Loza','Mauricio Pochettino Gil','Gerardo Martino Suárez','Edgardo Bauza Tapia','Gustavo Alfaro Mejía'],
  en: ['Gareth Palmer','Eddie Howe-Jones','Sean Dyche Cooper','Mark Robins Taylor','Kieran McKenna Shaw','Russell Martin Lowe','Gary O’Neil Fraser','Rob Edwards Miles','Thomas Frank Sørensen','Oliver Glasner Maier'],
  it: ['Carlo Mazzone Ferri','Roberto De Zerbi Vitali','Giancarlo Italiano Neri','Pierpaolo Inzaghi Renzi','Massimiliano Allegri Bassi','Sergio Conceição Alves','Eusebio Di Francesco Ricci','Vincenzo Montella Grasso','Maurizio Sarri Landi','Ivan Jurić Kos'],
  de: ['Jürgen Klopp Steiner','Thomas Tuchel Brandt','Hansi Flick Lehmann','Julian Nagelsmann Roth','Xabi Alonso Vega','Edin Terzić Bozic','Sebastian Hoeneß Baum','Marco Rose Fischer','Niko Kovač Peric','Oliver Glasner Sommer'],
  fr: ['Didier Deschamps Fabre','Christophe Galtier Roux','Bruno Génésio Blanc','Rudi Garcia Pons','Laurent Blanc Olivier','Luis Enrique Marco','Franck Haise Schmitt','Will Still Vandenbroeck','Pierre Sage Martin','Éric Roy Tessier'],
};

export const SPONSORS = ['VivaBank','AeroBrasil','NeoTech','BetMax','SolarEnergia','PrimeSeguros','UltraCell','NordBank','MaxPlay','VitaSaúde','PetroForte','GloboShop','AutoVia','TeleNorte','UniCafé','AstraGames'];
export const BOOT_BRANDS = [];

// -------------------- FORMAÇÕES / TÁTICAS --------------------
export const FORMATIONS = [
  { id: '4-4-2', d: 4, m: 4, a: 2 },
  { id: '4-3-3', d: 4, m: 3, a: 3 },
  { id: '4-2-3-1', d: 4, m: 5, a: 1 },
  { id: '3-5-2', d: 3, m: 5, a: 2 },
  { id: '3-4-3', d: 3, m: 4, a: 3 },
  { id: '5-3-2', d: 5, m: 3, a: 2 },
  { id: '4-5-1', d: 4, m: 5, a: 1 },
  { id: '4-1-4-1', d: 4, m: 5, a: 1 },
];
export const MENTALITIES = ['Defensivo', 'Equilibrado', 'Ofensivo'];
export const PRESSING = ['Baixa', 'Média', 'Alta'];
export const LINES = ['Recuada', 'Normal', 'Adiantada'];
export const STYLES = ['Posse de bola', 'Contra-ataque'];
export const TEMPO = ['Lento', 'Normal', 'Rápido'];

export const PERSONALITIES = ['Profissional', 'Líder', 'Ambicioso', 'Humilde', 'Pavio curto', 'Resiliente'];
export const POSITIONS = { G: 'Goleiro', D: 'Defensor', M: 'Meio-campo', A: 'Atacante' };
export const POS_ORDER = ['G', 'D', 'M', 'A'];

// -------------------- i18n (rótulos principais) --------------------
export const I18N = {
  pt: {
    home: 'Início', squad: 'Elenco', tactics: 'Táticas', play: 'Jogar', league: 'Liga', more: 'Mais',
    next: 'Próxima partida', table: 'Tabela', fixtures: 'Calendário', market: 'Mercado', finances: 'Finanças',
    club: 'Clube', youth: 'Base', manager: 'Treinador', training: 'Treinos', stats: 'Estatísticas', ranking: 'Ranking', settings: 'Configurações',
    saves: 'Saves', friendlies: 'Amistosos', custom: 'Criar Campeonato', credits: 'Créditos', cup: 'Copas',
    newGame: 'Novo Jogo', continue: 'Continuar', loadSave: 'Carregar Save', editor: 'Editor',
    teamOfWeek: 'Avançar', quick: 'Resultado rápido', live: 'Assistir', skip: 'Pular',
  },
  en: {
    home: 'Home', squad: 'Squad', tactics: 'Tactics', play: 'Play', league: 'League', more: 'More',
    next: 'Next match', table: 'Table', fixtures: 'Fixtures', market: 'Transfers', finances: 'Finances',
    club: 'Club', youth: 'Academy', manager: 'Manager', training: 'Training', stats: 'Stats', ranking: 'Ranking', settings: 'Settings',
    saves: 'Saves', friendlies: 'Friendlies', custom: 'Custom Cup', credits: 'Credits', cup: 'Cups',
    newGame: 'New Game', continue: 'Continue', loadSave: 'Load Save', editor: 'Editor',
    teamOfWeek: 'Advance', quick: 'Quick result', live: 'Watch', skip: 'Skip',
  },
};

// Nacionalidades adicionais (nomes reais de seleções fora das 9 jogáveis)
export const NAT_LABELS = {
  bel: 'Bélgica', col: 'Colômbia', uru: 'Uruguai', chi: 'Chile', par: 'Paraguai', per: 'Peru',
  ecu: 'Equador', ven: 'Venezuela', mex: 'México', usa: 'EUA', jpn: 'Japão', kor: 'Coreia do Sul',
  cro: 'Croácia', srb: 'Sérvia', pol: 'Polônia', ukr: 'Ucrânia', tur: 'Turquia', sui: 'Suíça',
  aut: 'Áustria', den: 'Dinamarca', nor: 'Noruega', swe: 'Suécia', sco: 'Escócia', wal: 'País de Gales',
  gre: 'Grécia', gha: 'Gana', nga: 'Nigéria', sen: 'Senegal', mar: 'Marrocos', alg: 'Argélia',
  egy: 'Egito', cmr: 'Camarões', civ: 'Costa do Marfim', mli: 'Mali', gui: 'Guiné', tog: 'Togo',
  gab: 'Gabão', con: 'Congo', cod: 'RD Congo', can: 'Canadá', irl: 'Irlanda', rus: 'Rússia',
  geo: 'Geórgia', alb: 'Albânia', ksa: 'Arábia Saudita', qat: 'Catar', aou: 'Austrália', aus: 'Austrália',
};

export const T = (lang, key) => (I18N[lang] && I18N[lang][key]) || I18N.pt[key] || key;

// ============================================================
// ADICIONAIS DO MODO CARREIRA (Vida de Craque 26)
// ============================================================

export const CITIES = {
  br: ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Porto Alegre', 'Salvador', 'Fortaleza', 'Curitiba', 'Recife', 'Santos', 'Goiânia', 'Niterói', 'Campinas', 'Manaus', 'Cuiabá', 'Vitória', 'Belém'],
  ar: ['Buenos Aires', 'Rosário', 'Córdoba', 'La Plata', 'Mendoza'],
  uy: ['Montevidéu', 'Paysandú', 'Salto'],
  co: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
  pt: ['Lisboa', 'Porto', 'Braga', 'Faro', 'Coimbra'],
  es: ['Madrid', 'Barcelona', 'Sevilha', 'Valência', 'Bilbao'],
  en: ['Londres', 'Manchester', 'Liverpool', 'Birmingham', 'Leeds'],
  fr: ['Paris', 'Lyon', 'Marselha', 'Lille', 'Nice'],
  de: ['Munique', 'Berlim', 'Dortmund', 'Hamburgo', 'Leipzig'],
  it: ['Roma', 'Milão', 'Nápoles', 'Turim', 'Florença'],
  nl: ['Amsterdã', 'Roterdã', 'Eindhoven'],
  be: ['Bruxelas', 'Antuérpia', 'Gante'],
  hr: ['Zagreb', 'Split', 'Rijeka'],
  rs: ['Belgrado', 'Novi Sad', 'Niš'],
  us: ['Miami', 'Los Angeles', 'Nova York', 'Atlanta', 'Seattle'],
  mx: ['Cidade do México', 'Monterrey', 'Guadalajara'],
  jp: ['Tóquio', 'Osaka', 'Yokohama'],
  kr: ['Seul', 'Busan', 'Incheon'],
  ng: ['Lagos', 'Abuja', 'Kano'],
  sn: ['Dacar', 'Touba', 'Thiès'],
  ma: ['Casablanca', 'Rabat', 'Marraquexe'],
  eg: ['Cairo', 'Alexandria', 'Gizé'],
};
export const POOL_BY_COUNTRY = {
  br: 'br', ar: 'hisp', uy: 'hisp', co: 'hisp', mx: 'hisp', es: 'hisp',
  en: 'en', us: 'en', it: 'it', de: 'de', nl: 'de', be: 'de', fr: 'fr',
  pt: 'br', hr: 'hisp', rs: 'hisp', jp: 'en', kr: 'en', ng: 'en', sn: 'fr', ma: 'fr', eg: 'en',
};
export const CAREER_POSITIONS = [
  { id: 'GOL', name: 'Goleiro', abbr: 'GOL', color: 'pos-G', icon: '🧤', desc: 'Defende a meta. Depende do atributo Goleiro.', w: { GOL: 0.62, DEF: 0.12, PHY: 0.10, PAS: 0.10, COM: 0.06 }, main: 'GOL' },
  { id: 'ZAG', name: 'Zagueiro', abbr: 'ZAG', color: 'pos-D', icon: '🛡️', desc: 'Rocha da defesa: marcação e jogo aéreo.', w: { DEF: 0.42, PHY: 0.26, PAS: 0.12, PAC: 0.10, DRI: 0.04, SHO: 0.04, COM: 0.02 }, main: 'DEF' },
  { id: 'LAT', name: 'Lateral', abbr: 'LAT', color: 'pos-D', icon: '🏃', desc: 'Sobe e desce o flanco o jogo inteiro.', w: { PAC: 0.30, DEF: 0.28, PAS: 0.18, PHY: 0.12, DRI: 0.06, SHO: 0.04, COM: 0.02 }, main: 'PAC' },
  { id: 'VOL', name: 'Volante', abbr: 'VOL', color: 'pos-D', icon: '⚔️', desc: 'Cão de guarda do meio: rouba e distribui.', w: { DEF: 0.28, PAS: 0.24, PHY: 0.20, PAC: 0.12, DRI: 0.08, SHO: 0.05, COM: 0.03 }, main: 'DEF' },
  { id: 'MC', name: 'Meia Central', abbr: 'MC', color: 'pos-M', icon: '🧭', desc: 'Dita o ritmo do jogo com passes.', w: { PAS: 0.30, DRI: 0.18, VIS: 0.14, PAC: 0.14, DEF: 0.12, PHY: 0.08, SHO: 0.04 }, main: 'PAS' },
  { id: 'MEI', name: 'Meia Ofensivo', abbr: 'MEI', color: 'pos-M', icon: '🎩', desc: 'Cria jogadas entre as linhas e finaliza.', w: { PAS: 0.28, DRI: 0.22, SHO: 0.15, VIS: 0.14, PAC: 0.12, PHY: 0.05, DEF: 0.04 }, main: 'PAS' },
  { id: 'PON', name: 'Ponta', abbr: 'PON', color: 'pos-A', icon: '⚡', desc: 'Velocidade e 1x1 na beirada do campo.', w: { PAC: 0.28, DRI: 0.25, SHO: 0.20, PAS: 0.14, VIS: 0.06, PHY: 0.05, DEF: 0.02 }, main: 'PAC' },
  { id: 'ATA', name: 'Atacante', abbr: 'ATA', color: 'pos-A', icon: '🎯', desc: 'A referência do gol: finalização e presença.', w: { SHO: 0.32, PAC: 0.20, DRI: 0.18, PAS: 0.12, PHY: 0.12, VIS: 0.04, DEF: 0.02 }, main: 'SHO' },
];
export const SKILLS = {
  PAC: { label: 'Ritmo', icon: '💨', group: 'fis' },
  SHO: { label: 'Chute', icon: '🎯', group: 'tec' },
  PAS: { label: 'Passe', icon: '🎳', group: 'tec' },
  DRI: { label: 'Drible', icon: '🌀', group: 'tec' },
  DEF: { label: 'Defesa', icon: '🛡️', group: 'tec' },
  PHY: { label: 'Físico', icon: '💪', group: 'fis' },
  VIS: { label: 'Visão', icon: '👁️', group: 'men' },
  LID: { label: 'Liderança', icon: '🗣️', group: 'men' },
  COM: { label: 'Compostura', icon: '🧘', group: 'men' },
  DET: { label: 'Determinação', icon: '🔥', group: 'men' },
  GOL: { label: 'Goleiro', icon: '🧤', group: 'tec' },
};
export const TECH_SKILLS = ['SHO', 'PAS', 'DRI', 'DEF'];
export const PHYS_SKILLS = ['PAC', 'PHY'];
export const MENTAL_SKILLS = ['VIS', 'LID', 'COM', 'DET'];
export const TRAITS = [
  { id: 'prof', name: 'Profissional', icon: '📋', desc: 'Rotina impecável: menos escândalos, melhor recuperação.' },
  { id: 'amb', name: 'Ambicioso', icon: '🚀', desc: 'Evolui mais rápido, mas exige clubes grandes para ser feliz.' },
  { id: 'hum', name: 'Humilde', icon: '🙏', desc: 'Felicidade estável mesmo quando as coisas não andam.' },
  { id: 'fog', name: 'Fogoso', icon: '🌶️', desc: 'Mais raça em campo… e mais cartões.' },
  { id: 'res', name: 'Resiliente', icon: '🛠️', desc: 'Volta mais rápido de lesões e de fases ruins.' },
  { id: 'car', name: 'Carismático', icon: '⭐', desc: 'Ganha fama e seguidores mais rápido.' },
  { id: 'est', name: 'Estudioso', icon: '📚', desc: 'Inteligência alta; escola vai bem.' },
  { id: 'fes', name: 'Festeiro', icon: '🎉', desc: 'Vive a vida: mais fama, mais risco de escândalo.' },
  { id: 'sor', name: 'Sortudo', icon: '🍀', desc: 'Eventos bons acontecem com mais frequência.' },
  { id: 'cab', name: 'Cabeça Fria', icon: '🧠', desc: 'Compostura altíssima nos momentos decisivos.' },
];
export const TRAININGS = [
  { id: 'sho', name: 'Finalização', icon: '🎯', skills: ['SHO', 'PAS'], desc: 'Arremates, chutes de fora e batidas de pênalti.' },
  { id: 'dri', name: 'Drible', icon: '🌀', skills: ['DRI', 'PAC'], desc: 'Fintas, condução de bola e 1x1.' },
  { id: 'pas', name: 'Passe', icon: '🎳', skills: ['PAS', 'VIS'], desc: 'Distribuição curta e longa, visão de jogo.' },
  { id: 'pac', name: 'Velocidade', icon: '💨', skills: ['PAC', 'PHY'], desc: 'Sprints e explosão muscular.' },
  { id: 'phy', name: 'Físico', icon: '💪', skills: ['PHY', 'DEF'], desc: 'Força, resistência e jogadas de contato.' },
  { id: 'def', name: 'Defesa', icon: '🛡️', skills: ['DEF', 'PHY'], desc: 'Marcação, desarme e posicionamento defensivo.' },
  { id: 'men', name: 'Mental', icon: '🧠', skills: ['COM', 'DET', 'VIS'], desc: 'Foco, liderança e leitura de jogo.' },
  { id: 'gol', name: 'Goleiro', icon: '🧤', skills: ['GOL'], desc: 'Defesas, saídas e jogo com os pés (só goleiros).' },
  { id: 'desc', name: 'Descanso', icon: '😴', skills: [], desc: 'Recupera energia e forma, sem risco de lesão.' },
];
export const AWARDS = [
  { id: 'artilheiro', name: 'Artilheiro da Liga', icon: '⚽' },
  { id: 'melhor_jogador', name: 'Melhor Jogador da Liga', icon: '🏅' },
  { id: 'revelacao', name: 'Revelação do Ano', icon: '🌟' },
  { id: 'bola_ouro', name: 'Bola de Ouro', icon: '🏆' },
  { id: 'chuteira', name: 'Chuteira de Ouro', icon: '👟' },
  { id: 'copa_campeao', name: 'Campeão da Copa', icon: '🏆' },
  { id: 'continental', name: 'Campeão Continental', icon: '🌎' },
  { id: 'mundial', name: 'Campeão Mundial', icon: '🌍' },
  { id: 'melhor_nt', name: 'Destaque da Seleção', icon: '🇧🇷' },
];
export const BRANDS = [
  { id: 'nike', name: 'Nike', icon: '👟', tier: 3 },
  { id: 'adidas', name: 'Adidas', icon: '👟', tier: 3 },
  { id: 'puma', name: 'Puma', icon: '👟', tier: 2 },
  { id: 'energia', name: 'Energia+', icon: '⚡', tier: 1 },
  { id: 'banco', name: 'BancoPrime', icon: '🏦', tier: 2 },
  { id: 'app', name: 'SocNet', icon: '📱', tier: 1 },
  { id: 'carro', name: 'Veloz Motors', icon: '🚗', tier: 2 },
  { id: 'refri', name: 'SodaPop', icon: '🥤', tier: 1 },
  { id: 'game', name: 'PlayMax', icon: '🎮', tier: 2 },
  { id: 'relogio', name: 'LuxTime', icon: '⌚', tier: 3 },
];
export const LIFESTYLES = [
  { id: 0, name: 'Humilde', icon: '🍚', cost: 0, happ: 0, fame: 0, desc: 'Vida simples, sem luxos. Sem custo fixo.' },
  { id: 1, name: 'Confortável', icon: '🏠', cost: 8000, happ: 8, fame: 1, desc: 'Apartamento bom, carro popular, restaurantes.' },
  { id: 2, name: 'Luxo', icon: '💎', cost: 60000, happ: 16, fame: 3, desc: 'Mansão, carros importados, viagens.' },
  { id: 3, name: 'Mega Estrela', icon: '👑', cost: 300000, happ: 24, fame: 6, desc: 'Jatinho, iate e festas épicas.' },
];
export const PURCHASES = [
  { id: 'carro_simples', name: 'Carro popular', icon: '🚗', price: 90000, happ: 5, fame: 0, needFame: 0 },
  { id: 'carro_esportivo', name: 'Carro esportivo', icon: '🏎️', price: 700000, happ: 12, fame: 3, needFame: 20 },
  { id: 'casa_apartamento', name: 'Apartamento próprio', icon: '🏢', price: 900000, happ: 10, fame: 0, needFame: 0 },
  { id: 'casa_mansao', name: 'Mansão', icon: '🏰', price: 6000000, happ: 18, fame: 6, needFame: 40 },
  { id: 'barco', name: 'Iate', icon: '⛵', price: 3500000, happ: 14, fame: 8, needFame: 50 },
  { id: 'jet', name: 'Jatinho', icon: '✈️', price: 12000000, happ: 16, fame: 10, needFame: 60 },
  { id: 'relogio', name: 'Relógio de luxo', icon: '⌚', price: 250000, happ: 6, fame: 2, needFame: 25 },
  { id: 'casa_pais', name: 'Casa para seus pais', icon: '🏡', price: 800000, happ: 12, fame: 2, needFame: 10 },
];
export const NARRATIVE = {
  shot: ['disparou de fora da área!', 'arriscou de longe, por cima do travessão!', 'bateu cruzado, tirando tinta da trave!', 'finalizou com perigo, o goleiro espalmou!'],
  chance: ['recebeu na entrada da área e limpou o marcador!', 'tabelou e invadiu a área, quase saiu o gol!', 'dominou no peito e girou em cima da marcação!', 'abriu espaço com um corte seco, a zaga cortou no susto!'],
  pass: ['distribuiu um lançamento perfeito para o ataque!', 'achou o companheiro em profundidade!', 'tocou de primeira e inverteu o jogo!', 'fez uma enfiada sensacional!'],
  dribble: ['passou pelo marcador com um drible desconcertante!', 'aplicou um elástico e foi para cima!', 'deu um corte seco e deixou o zagueiro sentado!', 'usou o corpo e protegeu a bola com maestria!'],
  tackle: ['roubou a bola com um carrinho perfeito!', 'se antecipou e desarmou com precisão!', 'fechou o espaço e recuperou a posse!', 'ganhou a dividida no chão!'],
  card: ['cometeu falta dura e levou cartão amarelo.', 'descarregou o braço e o árbitro marcou falta.', 'fez uma entrada forte e o juiz advertiu.'],
  save: ['voou no ângulo e salvou o time!', 'fez uma defesaça à queima-roupa!', 'saiu do gol e cortou o cruzamento no susto!', 'espalmou para escanteio uma bomba!'],
  goal: ['GOL! GOL! GOL! Que pintura de jogada!', 'GOL! Na rede! Explosão no estádio!', 'GOL! O craque fez a torcida explodir!', 'GOL! GOLAÇO! Não deu chances para o goleiro!'],
  assist: ['cruzou na medida e o companheiro só escorou: GOL!', 'deixou o atacante na cara do gol: GOL!', 'enfiou a bola e o companheiro bateu: GOL!'],
  own: ['chutou de qualquer jeito e o goleiro fez a defesa.', 'tentou o cruzamento e a zaga cortou.', 'bateu fraco, sem perigo.', 'a jogada não saiu como planejado.'],
};
export const positionById = (id) => CAREER_POSITIONS.find((p) => p.id === id) || CAREER_POSITIONS[CAREER_POSITIONS.length - 1];
export const countryById = (id) => COUNTRIES.find((c) => c.id === id);

// Tier de carreira (1-6) por liga do mundo real — usado no modo jogador
export const LEAGUE_TIER = {
  br1: 5, br2: 4, br3: 3, br4: 2,
  ar1: 4,
  en1: 6, es1: 6, it1: 6, de1: 5, fr1: 5, pt1: 4, nl1: 4,
};

// Textos adicionais do modo carreira (fundidos ao i18n principal)
Object.assign(I18N.pt, {
  training: 'Treino', play: 'Jogar', career: 'Carreira', market: 'Mercado',
  family: 'Família', money: 'Dinheiro', fame: 'Fama', more: 'Mais', inbox: 'Mensagens',
  settings: 'Configurações', saves: 'Saves', credits: 'Créditos', howto: 'Como Jogar',
  phone: 'Celular', social: 'Rede Social', immersion: 'Cidade',
  newGame: 'Novo Jogo', continue: 'Continuar', loadSave: 'Carregar Save',
  advance: 'Avançar mês', next: 'Próximo', home: 'Início',
});
Object.assign(I18N.en, {
  training: 'Training', play: 'Play', career: 'Career', market: 'Market',
  family: 'Family', money: 'Money', fame: 'Fame', more: 'More', inbox: 'Messages',
  settings: 'Settings', saves: 'Saves', credits: 'Credits', howto: 'How to Play',
  phone: 'Phone', social: 'Social', immersion: 'City',
  newGame: 'New Game', continue: 'Continue', loadSave: 'Load Save',
  advance: 'Advance month', next: 'Next', home: 'Home',
});
